### ISSUE TITLE
Web - Demo 'Not found' :-(

### ISSUE THREAD

**Issue by fenix011** [codesandcoffees/vuejs-landing-page#3]
at ... your awesome ,

https://vue-starter.ville.io/

thanks for

**Comment by iamdevlinph** [comment]
That's actually the demo of the creator of the boilerplate.

The demo of this repo is the one seen on the top, beside the description, which is [this](https://codesandcoffees.github.io/vuejs-landing-page/)

I will update the readme me clarify things.

Thanks 👍

**Comment by iamdevlinph** [comment]
I have updated the readme. The correct demo url should be shown now.

Closing this issue.
